### ISSUE TITLE
Installation fails on Macbook M1

### ISSUE THREAD

**Issue by antic11d** [TylerGubala/blenderpy#104]
**Describe the bug**
When I try to install package on Macbook M1, installation fails with the following error:
```console
ERROR: Command errored out with exit status 1:
     command: /Users/dimi/miniforge3/envs/hiwi/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/9g/8khxl7b90plffzrxrvsryn3m0000gn/T/pip-install-uqv60qot/bpy_fba45b9b2c154c7db8ebd1f078ab0b44/setup.py'"'"'; __file__='"'"'/private/var/folders/9g/8khxl7b90plffzrxrvsryn3m0000gn/T/pip-install-uqv60qot/bpy_fba45b9b2c154c7db8ebd1f078ab0b44/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/9g/8khxl7b90plffzrxrvsryn3m0000gn/T/pip-pip-egg-info-yv3zwror
         cwd: /private/var/folders/9g/8khxl7b90plffzrxrvsryn3m0000gn/T/pip-install-uqv60qot/bpy_fba45b9b2c154c7db8ebd1f078ab0b44/
    Complete output (16 lines):
    Traceback (most recent call last):
      File "/Users/dimi/miniforge3/envs/hiwi/lib/python3.9/tokenize.py", line 342, in find_cookie
        codec = lookup(encoding)
    LookupError: unknown encoding: future_fstrings

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/dimi/miniforge3/envs/hiwi/lib/python3.9/tokenize.py", line 394, in open
        encoding, lines = detect_encoding(buffer.readline)
      File "/Users/dimi/miniforge3/envs/hiwi/lib/python3.9/tokenize.py", line 381, in detect_encoding
        encoding = find_cookie(second)
      File "/Users/dimi/miniforge3/envs/hiwi/lib/python3.9/tokenize.py", line 350, in find_cookie
        raise SyntaxError(msg)
    SyntaxError: unknown encoding for '/private/var/folders/9g/8khxl7b90plffzrxrvsryn3m0000gn/T/pip-install-uqv60qot/bpy_fba45b9b2c154c7db8ebd1f078ab0b44/setup.py': future_fstrings
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bc/e2/20c6d56f1143e13c0fc24a7d987ee28e4949b8edbbbb1b66f705d129bdc5/bpy-0.0.0a0.tar.gz#sha256=b48c0348cccaf9ad316bccd3dc65fdc8422e4c310c79c85448b01ae7feb7f02e (from https://pypi.org/simple/bpy/) (requires-python:>=3.4.0). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement bpy (from versions: 0.0.0a0)
ERROR: No matching distribution found for bpy
```

**To Reproduce**
Try to install package bpy with pip: `pip install bpy`

**Expected behavior**
Installation finishes successfully.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.5.2

**Additional context**
I am aware that a requirement for this package is python version in [3.6, 3.8), but as M1 architecture can run natively only python 3.9, is there any chance that this requirement can be lifted?

**Comment by TylerGubala** [comment]
Sounds like you are going to have to build Python 3.7 from sources and then
run
know if you have any other questions
pip3 install bpy==2.91a0
bpy_post_install

Sorry, I don't control which version of python Blender targets. That would
be Blender Foundation.

Let me know if you need anything else.

**Comment by antic11d** [comment]
Hi @TylerGubala ,

I'll give it a try, even though I am not sure python 3.7 can even be built from source for M1 (arm) cpu architecture.
I will close this issue, and reopen it in case there's something else needed. 
Thanks!

**Comment by TylerGubala** [comment]
As long as M1 can complete C I think it will work okay.

Now will you be able to use the wheel I provide, that's pretty interesting
to me.
