### ISSUE TITLE
2.82 bpy is not compatible with Darwin Python 3.9.7

### ISSUE THREAD

**Issue by eherbut** [TylerGubala/blenderpy#115]
Blender version: 3.0.1

I have Blender bundled with version of Python 3.9.7
Output from Blender terminal:
`>>> import sys
>>> sys.version
'3.9.7 (default, Oct 19 2021, 11:51:13) \n[Clang 11.0.0 (clang-1100.0.33.8)]'`

Trying to install bpy package for my python (in system terminal):
` % python3.9 -V                
Python 3.9.7

% python3.9 -m pip install bpy            
Collecting bpy
  Using cached bpy-0.0.0a0.tar.gz (19 kB)
Using legacy 'setup.py install' for bpy, since package 'wheel' is not installed.
Installing collected packages: bpy
    Running setup.py install for bpy ... |^[[B^[[error
    ERROR: Command errored out with exit status 1:
     command: /Users/eherbut/.pyenv/versions/3.9.7/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jz/z6lc3l5n1z5b3n9rkhw35nhm0000gp/T/pip-install-eavqi88y/bpy_f8262f0d28d044a7bf415a0eca8c315d/setup.py'"'"'; __file__='"'"'/private/var/folders/jz/z6lc3l5n1z5b3n9rkhw35nhm0000gp/T/pip-install-eavqi88y/bpy_f8262f0d28d044a7bf415a0eca8c315d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/jz/z6lc3l5n1z5b3n9rkhw35nhm0000gp/T/pip-record-w9q70gw4/install-record.txt --single-version-externally-managed --compile --install-headers /Users/eherbut/.pyenv/versions/3.9.7/include/python3.9/bpy
         cwd: /private/var/folders/jz/z6lc3l5n1z5b3n9rkhw35nhm0000gp/T/pip-install-eavqi88y/bpy_f8262f0d28d044a7bf415a0eca8c315d/
    Complete output (54 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-11.6-x86_64-3.9
    creating build/lib.macosx-11.6-x86_64-3.9/blenderpy
    copying blenderpy/__init__.py -> build/lib.macosx-11.6-x86_64-3.9/blenderpy
    copying blenderpy/post_install.py -> build/lib.macosx-11.6-x86_64-3.9/blenderpy
    running build_ext
    Preparing the build environment
    Searching for compatible Blender online (this will take a while)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jz/z6lc3l5n1z5b3n9rkhw35nhm0000gp/T/pip-install-eavqi88y/bpy_f8262f0d28d044a7bf415a0eca8c315d/setup.py", line 288, in <module>
        setup(name='bpy',
      File "/Users/eherbut/.pyenv/versions/3.9.7/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/Users/eherbut/.pyenv/versions/3.9.7/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/eherbut/.pyenv/versions/3.9.7/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Users/eherbut/.pyenv/versions/3.9.7/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/eherbut/.pyenv/versions/3.9.7/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Users/eherbut/.pyenv/versions/3.9.7/lib/python3.9/distutils/command/install.py", line 546, in run
        self.run_command('build')
      File "/Users/eherbut/.pyenv/versions/3.9.7/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/eherbut/.pyenv/versions/3.9.7/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/eherbut/.pyenv/versions/3.9.7/lib/python3.9/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Users/eherbut/.pyenv/versions/3.9.7/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/eherbut/.pyenv/versions/3.9.7/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/jz/z6lc3l5n1z5b3n9rkhw35nhm0000gp/T/pip-install-eavqi88y/bpy_f8262f0d28d044a7bf415a0eca8c315d/setup.py", line 186, in run
        self.build_cmake(extension)
      File "/private/var/folders/jz/z6lc3l5n1z5b3n9rkhw35nhm0000gp/T/pip-install-eavqi88y/bpy_f8262f0d28d044a7bf415a0eca8c315d/setup.py", line 220, in build_cmake
        raise Exception(f"{VERSION} bpy is not compatible with "
    Exception: 2.82 bpy is not compatible with Darwin Python 3.9.7 (default, Feb 22 2022, 20:59:24)
    [Clang 13.0.0 (clang-1300.0.29.30)] 64bit
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/eherbut/.pyenv/versions/3.9.7/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jz/z6lc3l5n1z5b3n9rkhw35nhm0000gp/T/pip-install-eavqi88y/bpy_f8262f0d28d044a7bf415a0eca8c315d/setup.py'"'"'; __file__='"'"'/private/var/folders/jz/z6lc3l5n1z5b3n9rkhw35nhm0000gp/T/pip-install-eavqi88y/bpy_f8262f0d28d044a7bf415a0eca8c315d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/jz/z6lc3l5n1z5b3n9rkhw35nhm0000gp/T/pip-record-w9q70gw4/install-record.txt --single-version-externally-managed --compile --install-headers /Users/eherbut/.pyenv/versions/3.9.7/include/python3.9/bpy Check the logs for full command output.
`

Despite the fact my python version matches to what bundled with blander, Im not able to install bpy. 
I've checked simillar reports at this project and for all those cases authors had really different version python comparing to what they have in blender. But it's not my case.

**Comment by Psijic** [comment]
They say bpy 2.82.1 requires: Python >=3.7, <3.8
