### ISSUE TITLE
can't pip install bpy

### ISSUE THREAD

**Issue by ParastooJ** [TylerGubala/blenderpy#24]
Hello,

When I try pip install bpy, I get the following error message. Do you know what this might be about. I am using python 3.7.3.

> CMake Error at /home/parastooj/anaconda3/envs/emtoolschool/lib/python3.7/site-packages/cmake/data/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
      Could NOT find PythonLibsUnix (missing: PYTHON_LIBRARY PYTHON_LIBPATH
      PYTHON_INCLUDE_DIR PYTHON_INCLUDE_CONFIG_DIR)
    Call Stack (most recent call first):
      /home/parastooj/anaconda3/envs/emtoolschool/lib/python3.7/site-packages/cmake/data/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
      build_files/cmake/Modules/FindPythonLibsUnix.cmake:181 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      build_files/cmake/platform/platform_unix.cmake:83 (find_package)
      CMakeLists.txt:899 (include)

Thanks!

**Comment by TylerGubala** [comment]
Can you please provide some additional details about the error you are facing?

What is your environment? Am I correct in assuming it is Linux? CPython?

If no additional details are provided in a week I am going to close the issue.

**Comment by Rolandisimo** [comment]
Hi, I am on macOS Catalina 10.15.3. Installation errors out:

```
ERROR: Command errored out with exit status 1:
     command: /Users/rolands/Desktop/blender/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/34/s3rxmzvs6qg9pjtn29zgl3cc0000gp/T/pip-install-330kgjrz/bpy/setup.py'"'"'; __file__='"'"'/private/var/folders/34/s3rxmzvs6qg9pjtn29zgl3cc0000gp/T/pip-install-330kgjrz/bpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/34/s3rxmzvs6qg9pjtn29zgl3cc0000gp/T/pip-install-330kgjrz/bpy/pip-egg-info
         cwd: /private/var/folders/34/s3rxmzvs6qg9pjtn29zgl3cc0000gp/T/pip-install-330kgjrz/bpy/
    Complete output (16 lines):
    Traceback (most recent call last):
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/tokenize.py", line 397, in find_cookie
        codec = lookup(encoding)
    LookupError: unknown encoding: future_fstrings

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/tokenize.py", line 449, in open
        encoding, lines = detect_encoding(buffer.readline)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/tokenize.py", line 436, in detect_encoding
        encoding = find_cookie(second)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/tokenize.py", line 405, in find_cookie
        raise SyntaxError(msg)
    SyntaxError: unknown encoding for '/private/var/folders/34/s3rxmzvs6qg9pjtn29zgl3cc0000gp/T/pip-install-330kgjrz/bpy/setup.py': future_fstrings
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Any chance this could be revived?

**Comment by Rolandisimo** [comment]
UPDATE

Even though I am on python 3.7, I had to install these for the `bpy` installation to start:
- pip install -U future-fstrings
- pip install -U setuptools

**Comment by Rolandisimo** [comment]
Failed to install. Log:

```
(env) ➜  env pip install bpy
Collecting bpy
  Using cached bpy-1.2.3.tar.gz (20 kB)
Installing collected packages: bpy
    Running setup.py install for bpy ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/rolands/Desktop/blender/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/34/s3rxmzvs6qg9pjtn29zgl3cc0000gp/T/pip-install-y_kulgxf/bpy/setup.py'"'"'; __file__='"'"'/private/var/folders/34/s3rxmzvs6qg9pjtn29zgl3cc0000gp/T/pip-install-y_kulgxf/bpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/34/s3rxmzvs6qg9pjtn29zgl3cc0000gp/T/pip-record-0i7dnf5j/install-record.txt --single-version-externally-managed --compile --install-headers /Users/rolands/Desktop/blender/env/include/site/python3.7/bpy
         cwd: /private/var/folders/34/s3rxmzvs6qg9pjtn29zgl3cc0000gp/T/pip-install-y_kulgxf/bpy/
    Complete output (47 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    running install
    running build
    running build_ext
    Preparing the build environment
    Cloning Blender source from git://git.blender.org/blender.git
    Updating Blender git submodules
    Configuring cmake project
    cmake -H/Users/rolands/.blenderpy/blender -Bbuild/temp.macosx-10.14-x86_64-3.7 -DWITH_PLAYER=OFF -DWITH_PYTHON_INSTALL=OFF -DWITH_PYTHON_MODULE=ON
    -- The C compiler identification is AppleClang 11.0.0.11000033
    -- The CXX compiler identification is AppleClang 11.0.0.11000033
    -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
    -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
    xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
    CMake Error at build_files/cmake/platform/platform_apple_xcode.cmake:73 (string):
      string begin index: 6 is out of range 0 - 0
    Call Stack (most recent call first):
      CMakeLists.txt:564 (include)


    -- Detected OS X  and Xcode  at /Library/Developer/CommandLineTools
    CMake Error at build_files/cmake/platform/platform_apple_xcode.cmake:79 (if):
      if given arguments:

        "VERSION_LESS" "4.3"

      Unknown arguments specified
    Call Stack (most recent call first):
      CMakeLists.txt:564 (include)


    -- Configuring incomplete, errors occurred!
    See also "/private/var/folders/34/s3rxmzvs6qg9pjtn29zgl3cc0000gp/T/pip-install-y_kulgxf/bpy/build/temp.macosx-10.14-x86_64-3.7/CMakeFiles/CMakeOutput.log".
    error: command 'cmake' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/rolands/Desktop/blender/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/34/s3rxmzvs6qg9pjtn29zgl3cc0000gp/T/pip-install-y_kulgxf/bpy/setup.py'"'"'; __file__='"'"'/private/var/folders/34/s3rxmzvs6qg9pjtn29zgl3cc0000gp/T/pip-install-y_kulgxf/bpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/34/s3rxmzvs6qg9pjtn29zgl3cc0000gp/T/pip-record-0i7dnf5j/install-record.txt --single-version-externally-managed --compile --install-headers /Users/rolands/Desktop/blender/env/include/site/python3.7/bpy Check the logs for full command output.
(env) ➜  env
```

**Comment by TylerGubala** [comment]
@Rolandisimo If you are on MacOS, then please see [this link](https://github.com/TylerGubala/blenderpy/wiki/Platform---MacoOS)

Please follow the discussion of the Mac platform at issue #2 ; I have not been able to push this out as a pip-installable due to various inconsistencies that I have faced with different platforms. I am hoping people with domain experience can assist in by contributing! I am primarily a Windows developer, so it's kind of like learning a foreign language for me.

Thanks for your patience.
