### ISSUE TITLE
AttributeError: 'Distribution' object has no attribute 'bin_dir'

### ISSUE THREAD

**Issue by fanhaidi** [TylerGubala/blenderpy#27]
I use 
python setup.py install 
on windows10 python 3.6

running install
running bdist_egg
running egg_info
writing bpy.egg-info\PKG-INFO
writing dependency_links to bpy.egg-info\dependency_links.txt
writing requirements to bpy.egg-info\requires.txt
writing top-level names to bpy.egg-info\top_level.txt
reading manifest file 'bpy.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'bpy.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
warning: install_lib: 'build\lib' does not exist -- no Python modules to install

........
........

Moving library files
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
    yield saved
  File "C:\Anaconda3\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
    yield
  File "C:\Anaconda3\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "C:\Anaconda3\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "C:\Users\haidifan\AppData\Local\Temp\easy_install-w31suz7m\bpy-build-1.0.2a0\setup.py", line 398, in <module>
  File "C:\Anaconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "C:\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\haidifan\AppData\Local\Temp\easy_install-w31suz7m\bpy-build-1.0.2a0\setup.py", line 82, in run
AttributeError: 'Distribution' object has no attribute 'bin_dir'

**Comment by TylerGubala** [comment]
Setup.py is not meant to be run directly from this repo.

I know that's confusing, and there should be  a fix in the near future but
for now please just run

py -m pip install bpy

In whatever pythin 3.6 Windows 10 environment you want to install it in

**Comment by TylerGubala** [comment]
Setup.py can now be run from this repo directly. Info in `README.md`

**Comment by shawkontzu** [comment]
Hi @TylerGubala 
I am trying to install bpy by running your install script setup.py under blenderpy root dir. At the end of compilation this error still pops up
`AttributeError: 'Distribution' object has no attribute 'bin_dir'`

OS: ubuntu 18
python: 3.7
setuptools: 54.2.0
