### ISSUE TITLE
Error building wheel.

### ISSUE THREAD

**Issue by Lucoa-Kamui** [TylerGubala/blenderpy#35]
I am trying to pip install bpy but it wont work. I did everything that was said in the README.md file.
I am using python 3.6.8 here is the error log:

<details><summary>Click to expand</summary>

```
C:\Users\blade>pip install bpy-cuda
Collecting bpy-cuda
  Downloading bpy-cuda-0.0.0a0.tar.gz (19 kB)
Building wheels for collected packages: bpy-cuda
  Building wheel for bpy-cuda (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\blade\appdata\local\programs\python\python36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\blade\\AppData\\Local\\Temp\\pip-install-qvry82c3\\bpy-cuda\\setup.py'"'"'; __file__='"'"'C:\\Users\\blade\\AppData\\Local\\Temp\\pip-install-qvry82c3\\bpy-cuda\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\blade\AppData\Local\Temp\pip-wheel-sa5343bu'
       cwd: C:\Users\blade\AppData\Local\Temp\pip-install-qvry82c3\bpy-cuda\
  Complete output (85 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\blenderpy
  copying blenderpy\post_install.py -> build\lib.win-amd64-3.6\blenderpy
  copying blenderpy\__init__.py -> build\lib.win-amd64-3.6\blenderpy
  running build_ext
  Traceback (most recent call last):
    File "c:\users\blade\appdata\local\temp\pip-install-qvry82c3\bpy-cuda\.eggs\gitpython-3.1.2-py3.6.egg\git\__init__.py", line 83, in <module>
      refresh()
    File "c:\users\blade\appdata\local\temp\pip-install-qvry82c3\bpy-cuda\.eggs\gitpython-3.1.2-py3.6.egg\git\__init__.py", line 73, in refresh
      if not Git.refresh(path=path):
    File "c:\users\blade\appdata\local\temp\pip-install-qvry82c3\bpy-cuda\.eggs\gitpython-3.1.2-py3.6.egg\git\cmd.py", line 278, in refresh
      raise ImportError(err)
  ImportError: Bad git executable.
  The git executable must be specified in one of the following ways:
      - be included in your $PATH
      - be set via $GIT_PYTHON_GIT_EXECUTABLE
      - explicitly set via git.refresh()

  All git commands will error until this is rectified.

  This initial warning can be silenced or aggravated in the future by setting the
  $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
      - quiet|q|silence|s|none|n|0: for no warning or exception
      - warn|w|warning|1: for a printed warning
      - error|e|raise|r|2: for a raised exception

  Example:
      export GIT_PYTHON_REFRESH=quiet


  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\blade\AppData\Local\Temp\pip-install-qvry82c3\bpy-cuda\setup.py", line 345, in <module>
      'install_scripts': InstallBlenderScripts
    File "c:\users\blade\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 143, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\blade\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\blade\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "c:\users\blade\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\blade\AppData\Roaming\Python\Python36\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "c:\users\blade\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\blade\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\blade\appdata\local\programs\python\python36\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\blade\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\blade\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\blade\AppData\Local\Temp\pip-install-qvry82c3\bpy-cuda\setup.py", line 194, in run
      self.build_cmake(extension)
    File "C:\Users\blade\AppData\Local\Temp\pip-install-qvry82c3\bpy-cuda\setup.py", line 205, in build_cmake
      import bpybuild.sources
    File "c:\users\blade\appdata\local\temp\pip-install-qvry82c3\bpy-cuda\.eggs\bpy_build-1.1.8-py3.6.egg\bpybuild\sources.py", line 20, in <module>
      import git
    File "c:\users\blade\appdata\local\temp\pip-install-qvry82c3\bpy-cuda\.eggs\gitpython-3.1.2-py3.6.egg\git\__init__.py", line 85, in <module>
      raise ImportError('Failed to initialize: {0}'.format(exc))
  ImportError: Failed to initialize: Bad git executable.
  The git executable must be specified in one of the following ways:
      - be included in your $PATH
      - be set via $GIT_PYTHON_GIT_EXECUTABLE
      - explicitly set via git.refresh()

  All git commands will error until this is rectified.

  This initial warning can be silenced or aggravated in the future by setting the
  $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
      - quiet|q|silence|s|none|n|0: for no warning or exception
      - warn|w|warning|1: for a printed warning
      - error|e|raise|r|2: for a raised exception

  Example:
      export GIT_PYTHON_REFRESH=quiet

  ----------------------------------------
  ERROR: Failed building wheel for bpy-cuda
  Running setup.py clean for bpy-cuda
Failed to build bpy-cuda
Installing collected packages: bpy-cuda
    Running setup.py install for bpy-cuda ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\blade\appdata\local\programs\python\python36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\blade\\AppData\\Local\\Temp\\pip-install-qvry82c3\\bpy-cuda\\setup.py'"'"'; __file__='"'"'C:\\Users\\blade\\AppData\\Local\\Temp\\pip-install-qvry82c3\\bpy-cuda\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\blade\AppData\Local\Temp\pip-record-gi8zktng\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\blade\appdata\local\programs\python\python36\Include\bpy-cuda'
         cwd: C:\Users\blade\AppData\Local\Temp\pip-install-qvry82c3\bpy-cuda\
    Complete output (87 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\blenderpy
    copying blenderpy\post_install.py -> build\lib.win-amd64-3.6\blenderpy
    copying blenderpy\__init__.py -> build\lib.win-amd64-3.6\blenderpy
    running build_ext
    Traceback (most recent call last):
      File "c:\users\blade\appdata\local\temp\pip-install-qvry82c3\bpy-cuda\.eggs\gitpython-3.1.2-py3.6.egg\git\__init__.py", line 83, in <module>
        refresh()
      File "c:\users\blade\appdata\local\temp\pip-install-qvry82c3\bpy-cuda\.eggs\gitpython-3.1.2-py3.6.egg\git\__init__.py", line 73, in refresh
        if not Git.refresh(path=path):
      File "c:\users\blade\appdata\local\temp\pip-install-qvry82c3\bpy-cuda\.eggs\gitpython-3.1.2-py3.6.egg\git\cmd.py", line 278, in refresh
        raise ImportError(err)
    ImportError: Bad git executable.
    The git executable must be specified in one of the following ways:
        - be included in your $PATH
        - be set via $GIT_PYTHON_GIT_EXECUTABLE
        - explicitly set via git.refresh()

    All git commands will error until this is rectified.

    This initial warning can be silenced or aggravated in the future by setting the
    $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
        - quiet|q|silence|s|none|n|0: for no warning or exception
        - warn|w|warning|1: for a printed warning
        - error|e|raise|r|2: for a raised exception

    Example:
        export GIT_PYTHON_REFRESH=quiet


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\blade\AppData\Local\Temp\pip-install-qvry82c3\bpy-cuda\setup.py", line 345, in <module>
        'install_scripts': InstallBlenderScripts
      File "c:\users\blade\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\blade\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\blade\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\blade\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\blade\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\blade\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\blade\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\blade\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\blade\appdata\local\programs\python\python36\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\blade\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\blade\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\blade\AppData\Local\Temp\pip-install-qvry82c3\bpy-cuda\setup.py", line 194, in run
        self.build_cmake(extension)
      File "C:\Users\blade\AppData\Local\Temp\pip-install-qvry82c3\bpy-cuda\setup.py", line 205, in build_cmake
        import bpybuild.sources
      File "c:\users\blade\appdata\local\temp\pip-install-qvry82c3\bpy-cuda\.eggs\bpy_build-1.1.8-py3.6.egg\bpybuild\sources.py", line 20, in <module>
        import git
      File "c:\users\blade\appdata\local\temp\pip-install-qvry82c3\bpy-cuda\.eggs\gitpython-3.1.2-py3.6.egg\git\__init__.py", line 85, in <module>
        raise ImportError('Failed to initialize: {0}'.format(exc))
    ImportError: Failed to initialize: Bad git executable.
    The git executable must be specified in one of the following ways:
        - be included in your $PATH
        - be set via $GIT_PYTHON_GIT_EXECUTABLE
        - explicitly set via git.refresh()

    All git commands will error until this is rectified.

    This initial warning can be silenced or aggravated in the future by setting the
    $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
        - quiet|q|silence|s|none|n|0: for no warning or exception
        - warn|w|warning|1: for a printed warning
        - error|e|raise|r|2: for a raised exception

    Example:
        export GIT_PYTHON_REFRESH=quiet

    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\blade\appdata\local\programs\python\python36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\blade\\AppData\\Local\\Temp\\pip-install-qvry82c3\\bpy-cuda\\setup.py'"'"'; __file__='"'"'C:\\Users\\blade\\AppData\\Local\\Temp\\pip-install-qvry82c3\\bpy-cuda\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\blade\AppData\Local\Temp\pip-record-gi8zktng\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\blade\appdata\local\programs\python\python36\Include\bpy-cuda' Check the logs for full command output.
```

</details>

**Comment by TylerGubala** [comment]
I will link [the Wiki](https://github.com/TylerGubala/blenderpy/wiki#option-2---build-from-sources-using-pypi) in the readme about the prerequisites to building from an `sdist`.

**Comment by TylerGubala** [comment]
Fixed the readme. 

Your errors - you need `git` and `svn` installed. That's why its complaining about no `git` executable. You also need all of the prerequisites listed for your platform. You have to see the blender wiki for that.

By the way for python 3.6.8 you will have better results building from the repo. Alternatively you can install python 3.7. Wheels are coming out (then you wont have to do the multi hour long build by yourself) but are pending pypi upload file size limit increases.
