### ISSUE TITLE
Exception: 2.82 bpy is not compatible with Linux Python 3.6.9

### ISSUE THREAD

**Issue by YunYang1994** [TylerGubala/blenderpy#82]
~/bpy-build(master) » pip install bpy && bpy_post_install                                                                                                                                                                   yang@yang-MS-7B17
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Collecting bpy
  Using cached bpy-0.0.0a0.tar.gz (19 kB)
Building wheels for collected packages: bpy
  Building wheel for bpy (setup.py) ... -
```
error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zrk0kz96/bpy_62d6af21f50a4aed920874cc6930e5d8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zrk0kz96/bpy_62d6af21f50a4aed920874cc6930e5d8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-alpjj_a9
       cwd: /tmp/pip-install-zrk0kz96/bpy_62d6af21f50a4aed920874cc6930e5d8/
  Complete output (41 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/blenderpy
  copying blenderpy/post_install.py -> build/lib.linux-x86_64-3.6/blenderpy
  copying blenderpy/__init__.py -> build/lib.linux-x86_64-3.6/blenderpy
  running build_ext
  Preparing the build environment
  Searching for compatible Blender online (this will take a while)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-zrk0kz96/bpy_62d6af21f50a4aed920874cc6930e5d8/setup.py", line 335, in <module>
      'install_scripts': InstallBlenderScripts
    File "/home/yang/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/yang/.local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-zrk0kz96/bpy_62d6af21f50a4aed920874cc6930e5d8/setup.py", line 186, in run
      self.build_cmake(extension)
    File "/tmp/pip-install-zrk0kz96/bpy_62d6af21f50a4aed920874cc6930e5d8/setup.py", line 220, in build_cmake
      raise Exception(f"{VERSION} bpy is not compatible with "
  Exception: 2.82 bpy is not compatible with Linux Python 3.6.9 (default, Jan 26 2021, 15:33:00)
  [GCC 8.4.0] 64bit
  ----------------------------------------
  ERROR: Failed building wheel for bpy
```

**Comment by TylerGubala** [comment]
When you download Blender `2.82`, you get Python `3.7`.

Please upgrade to Python `3.7`

**Comment by frankkim1108** [comment]
Hi I have python 3.7.13 but still got the error message

``` Exception: 2.82 bpy is not compatible with Linux Python 3.7.13 ```

**Comment by KAKuzmichev** [comment]
2.82 bpy is not compatible with Linux Python 3.9.7
