### ISSUE TITLE
Exception: 2.82 bpy is not compatible with Linux Python 3.9.2

### ISSUE THREAD

**Issue by faaafo** [TylerGubala/blenderpy#84]
I've built blender as suggested[0], now running

`sudo pip install bpy && bpy_post_install`

returns

```
Collecting bpy
  Using cached bpy-0.0.0a0.tar.gz (19 kB)
Building wheels for collected packages: bpy
  Building wheel for bpy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-o0tlgkr2/bpy_62350f9b482c410599a0ce3f925baf6d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-o0tlgkr2/bpy_62350f9b482c410599a0ce3f925baf6d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-h385_yoq
       cwd: /tmp/pip-install-o0tlgkr2/bpy_62350f9b482c410599a0ce3f925baf6d/
  Complete output (41 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/blenderpy
  copying blenderpy/post_install.py -> build/lib.linux-x86_64-3.9/blenderpy
  copying blenderpy/__init__.py -> build/lib.linux-x86_64-3.9/blenderpy
  running build_ext
  Preparing the build environment
  Searching for compatible Blender online (this will take a while)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-o0tlgkr2/bpy_62350f9b482c410599a0ce3f925baf6d/setup.py", line 288, in <module>
      setup(name='bpy',
    File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-o0tlgkr2/bpy_62350f9b482c410599a0ce3f925baf6d/setup.py", line 186, in run
      self.build_cmake(extension)
    File "/tmp/pip-install-o0tlgkr2/bpy_62350f9b482c410599a0ce3f925baf6d/setup.py", line 220, in build_cmake
      raise Exception(f"{VERSION} bpy is not compatible with "
  Exception: 2.82 bpy is not compatible with Linux Python 3.9.2 (default, Feb 20 2021, 18:40:11)
  [GCC 10.2.0] 64bit
  ----------------------------------------
  ERROR: Failed building wheel for bpy
  Running setup.py clean for bpy
Failed to build bpy
Installing collected packages: bpy
    Running setup.py install for bpy ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-o0tlgkr2/bpy_62350f9b482c410599a0ce3f925baf6d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-o0tlgkr2/bpy_62350f9b482c410599a0ce3f925baf6d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-8c8d539y/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/bpy
         cwd: /tmp/pip-install-o0tlgkr2/bpy_62350f9b482c410599a0ce3f925baf6d/
    Complete output (43 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/blenderpy
    copying blenderpy/post_install.py -> build/lib.linux-x86_64-3.9/blenderpy
    copying blenderpy/__init__.py -> build/lib.linux-x86_64-3.9/blenderpy
    running build_ext
    Preparing the build environment
    Searching for compatible Blender online (this will take a while)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-o0tlgkr2/bpy_62350f9b482c410599a0ce3f925baf6d/setup.py", line 288, in <module>
        setup(name='bpy',
      File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.9/distutils/command/install.py", line 546, in run
        self.run_command('build')
      File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-o0tlgkr2/bpy_62350f9b482c410599a0ce3f925baf6d/setup.py", line 186, in run
        self.build_cmake(extension)
      File "/tmp/pip-install-o0tlgkr2/bpy_62350f9b482c410599a0ce3f925baf6d/setup.py", line 220, in build_cmake
        raise Exception(f"{VERSION} bpy is not compatible with "
    Exception: 2.82 bpy is not compatible with Linux Python 3.9.2 (default, Feb 20 2021, 18:40:11)
    [GCC 10.2.0] 64bit
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-o0tlgkr2/bpy_62350f9b482c410599a0ce3f925baf6d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-o0tlgkr2/bpy_62350f9b482c410599a0ce3f925baf6d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-8c8d539y/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/bpy Check the logs for full command output.
```
What else can I try?

Thank you for that tremendous amount of value you've created here

[0] https://wiki.blender.org/wiki/Building_Blender/Linux/Arch

**Comment by TylerGubala** [comment]
Please install Python 3.7.X; that's the version of Python that Blender is compatible with.

From the Blender integrated Python terminal:

```python
>>> import sys
>>> sys.version
'3.7.7 (default, Jun 13 2020, 11:11:23) [MSC v.1916 64 bit (AMD64)]'
```

Let me know if you need additional help.
