### ISSUE TITLE
Cannot install bpy: [Errno 2] No such file or directory: 'svn': 'svn'

### ISSUE THREAD

**Issue by ALLIESXO** [TylerGubala/blenderpy#88]
**Describe the bug**
Error when installing bpy using "pip install bpy" 

**Error Message **
  ERROR: Command errored out with exit status 1:
   command: /home/alexander/anaconda3/envs/vibe-env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i2tt25l0/bpy_a184597edbf643b581317b673bac9cbb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i2tt25l0/bpy_a184597edbf643b581317b673bac9cbb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-fdq9xnm9
       cwd: /tmp/pip-install-i2tt25l0/bpy_a184597edbf643b581317b673bac9cbb/
  Complete output (13 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/blenderpy
  copying blenderpy/__init__.py -> build/lib.linux-x86_64-3.7/blenderpy
  copying blenderpy/post_install.py -> build/lib.linux-x86_64-3.7/blenderpy
  copying blenderpy/pre_uninstall.py -> build/lib.linux-x86_64-3.7/blenderpy
  running build_ext
  Preparing the build environment
  Searching for compatible Blender online (this will take a while)
  error: [Errno 2] No such file or directory: 'svn': 'svn'
  ----------------------------------------
  ERROR: Failed building wheel for bpy
  Running setup.py clean for bpy
Failed to build bpy
Installing collected packages: bpy
    Running setup.py install for bpy ... error
    ERROR: Command errored out with exit status 1:
     command: /home/alexander/anaconda3/envs/vibe-env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i2tt25l0/bpy_a184597edbf643b581317b673bac9cbb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i2tt25l0/bpy_a184597edbf643b581317b673bac9cbb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-tvk4djvk/install-record.txt --single-version-externally-managed --compile --install-headers /home/alexander/anaconda3/envs/vibe-env/include/python3.7m/bpy
         cwd: /tmp/pip-install-i2tt25l0/bpy_a184597edbf643b581317b673bac9cbb/
    Complete output (13 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/blenderpy
    copying blenderpy/__init__.py -> build/lib.linux-x86_64-3.7/blenderpy
    copying blenderpy/post_install.py -> build/lib.linux-x86_64-3.7/blenderpy
    copying blenderpy/pre_uninstall.py -> build/lib.linux-x86_64-3.7/blenderpy
    running build_ext
    Preparing the build environment
    Searching for compatible Blender online (this will take a while)
    error: [Errno 2] No such file or directory: 'svn': 'svn'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/alexander/anaconda3/envs/vibe-env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i2tt25l0/bpy_a184597edbf643b581317b673bac9cbb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i2tt25l0/bpy_a184597edbf643b581317b673bac9cbb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-tvk4djvk/install-record.txt --single-version-externally-managed --compile --install-headers /home/alexander/anaconda3/envs/vibe-env/include/python3.7m/bpy Check the logs for full command output.

**Desktop (please complete the following information):**
 - OS:  Ubuntu 20.04

**Comment by YuzhouGuo** [comment]
**Similar `svn` Issue here**

This is what I got from `pip install bpy` in eclipse with PyDev installed

```
Collecting bpy
  Using cached bpy-2.82.1.tar.gz (19 kB)
Building wheels for collected packages: bpy
  Building wheel for bpy (setup.py): started
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.7/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hf/z6y_nh7s31v68qwvngk1s85w0000gn/T/pip-install-7t20rqx6/bpy_cd850d780e2c4c4d8bf1764790a94d28/setup.py'"'"'; __file__='"'"'/private/var/folders/hf/z6y_nh7s31v68qwvngk1s85w0000gn/T/pip-install-7t20rqx6/bpy_cd850d780e2c4c4d8bf1764790a94d28/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/hf/z6y_nh7s31v68qwvngk1s85w0000gn/T/pip-wheel-nqwy0mb9
       cwd: /private/var/folders/hf/z6y_nh7s31v68qwvngk1s85w0000gn/T/pip-install-7t20rqx6/bpy_cd850d780e2c4c4d8bf1764790a94d28/
  Complete output (60 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.15-x86_64-3.7
  creating build/lib.macosx-10.15-x86_64-3.7/blenderpy
  copying blenderpy/__init__.py -> build/lib.macosx-10.15-x86_64-3.7/blenderpy
  copying blenderpy/pre_uninstall.py -> build/lib.macosx-10.15-x86_64-3.7/blenderpy
  copying blenderpy/post_install.py -> build/lib.macosx-10.15-x86_64-3.7/blenderpy
  running build_ext
  Preparing the build environment
  Searching for compatible Blender online (this will take a while)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/hf/z6y_nh7s31v68qwvngk1s85w0000gn/T/pip-install-7t20rqx6/bpy_cd850d780e2c4c4d8bf1764790a94d28/setup.py", line 334, in <module>
      'install_scripts': InstallBlenderScripts
    File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python@3.7/3.7.10_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python@3.7/3.7.10_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python@3.7/3.7.10_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/local/Cellar/python@3.7/3.7.10_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.7/3.7.10_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python@3.7/3.7.10_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python@3.7/3.7.10_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.7/3.7.10_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/hf/z6y_nh7s31v68qwvngk1s85w0000gn/T/pip-install-7t20rqx6/bpy_cd850d780e2c4c4d8bf1764790a94d28/setup.py", line 186, in run
      self.build_cmake(extension)
    File "/private/var/folders/hf/z6y_nh7s31v68qwvngk1s85w0000gn/T/pip-install-7t20rqx6/bpy_cd850d780e2c4c4d8bf1764790a94d28/setup.py", line 216, in build_cmake
      compatible_bpy = bpybuild.sources.get_compatible_sources()
    File "/usr/local/lib/python3.7/site-packages/bpybuild/sources.py", line 393, in get_compatible_sources
      matched_version_dict = get_matched_versions()
    File "/usr/local/lib/python3.7/site-packages/bpybuild/sources.py", line 376, in get_matched_versions
      svns = svn_tags()
    File "/usr/local/lib/python3.7/site-packages/bpybuild/sources.py", line 361, in svn_tags
      return [BlenderSvn(tag_full_path) for tag_full_path in BlenderSvn.tags()]
    File "/usr/local/lib/python3.7/site-packages/bpybuild/sources.py", line 265, in tags
      cls.BASE_REPO.list(rel_path="/tags") if
    File "/usr/local/lib/python3.7/site-packages/bpybuild/sources.py", line 264, in <listcomp>
      return [posixpath.join(cls.BASE_URL, "tags", _version) for _version in
    File "/Users/yuzhouguo/Library/Python/3.7/lib/python/site-packages/svn/common.py", line 341, in list
      [full_url_or_path]):
    File "/Users/yuzhouguo/Library/Python/3.7/lib/python/site-packages/svn/common.py", line 60, in run_command
      return self.external_command(cmd, environment=self.__env, **kwargs)
    File "/Users/yuzhouguo/Library/Python/3.7/lib/python/site-packages/svn/common_base.py", line 39, in external_command
      return_code, cmd, stdout))
  svn.exception.SvnException: Command failed with (72): ['svn', '--non-interactive', 'ls', 'https://svn.blender.org/svnroot/bf-blender//tags']
  svn: error: Failed to locate 'svn'.
  svn: error: The subversion command line tools are no longer provided by Xcode.
  
  ----------------------------------------
  ERROR: Failed building wheel for bpy
  Building wheel for bpy (setup.py): finished with status 'error'
  Running setup.py clean for bpy
Failed to build bpy
Installing collected packages: bpy
    Running setup.py install for bpy: started
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.7/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hf/z6y_nh7s31v68qwvngk1s85w0000gn/T/pip-install-7t20rqx6/bpy_cd850d780e2c4c4d8bf1764790a94d28/setup.py'"'"'; __file__='"'"'/private/var/folders/hf/z6y_nh7s31v68qwvngk1s85w0000gn/T/pip-install-7t20rqx6/bpy_cd850d780e2c4c4d8bf1764790a94d28/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/hf/z6y_nh7s31v68qwvngk1s85w0000gn/T/pip-record-znq4la65/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/bpy
         cwd: /private/var/folders/hf/z6y_nh7s31v68qwvngk1s85w0000gn/T/pip-install-7t20rqx6/bpy_cd850d780e2c4c4d8bf1764790a94d28/
    Complete output (62 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.15-x86_64-3.7
    creating build/lib.macosx-10.15-x86_64-3.7/blenderpy
    copying blenderpy/__init__.py -> build/lib.macosx-10.15-x86_64-3.7/blenderpy
    copying blenderpy/pre_uninstall.py -> build/lib.macosx-10.15-x86_64-3.7/blenderpy
    copying blenderpy/post_install.py -> build/lib.macosx-10.15-x86_64-3.7/blenderpy
    running build_ext
    Preparing the build environment
    Searching for compatible Blender online (this will take a while)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hf/z6y_nh7s31v68qwvngk1s85w0000gn/T/pip-install-7t20rqx6/bpy_cd850d780e2c4c4d8bf1764790a94d28/setup.py", line 334, in <module>
        'install_scripts': InstallBlenderScripts
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python@3.7/3.7.10_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python@3.7/3.7.10_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python@3.7/3.7.10_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python@3.7/3.7.10_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/Cellar/python@3.7/3.7.10_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.7/3.7.10_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python@3.7/3.7.10_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python@3.7/3.7.10_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.7/3.7.10_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/hf/z6y_nh7s31v68qwvngk1s85w0000gn/T/pip-install-7t20rqx6/bpy_cd850d780e2c4c4d8bf1764790a94d28/setup.py", line 186, in run
        self.build_cmake(extension)
      File "/private/var/folders/hf/z6y_nh7s31v68qwvngk1s85w0000gn/T/pip-install-7t20rqx6/bpy_cd850d780e2c4c4d8bf1764790a94d28/setup.py", line 216, in build_cmake
        compatible_bpy = bpybuild.sources.get_compatible_sources()
      File "/usr/local/lib/python3.7/site-packages/bpybuild/sources.py", line 393, in get_compatible_sources
        matched_version_dict = get_matched_versions()
      File "/usr/local/lib/python3.7/site-packages/bpybuild/sources.py", line 376, in get_matched_versions
        svns = svn_tags()
      File "/usr/local/lib/python3.7/site-packages/bpybuild/sources.py", line 361, in svn_tags
        return [BlenderSvn(tag_full_path) for tag_full_path in BlenderSvn.tags()]
      File "/usr/local/lib/python3.7/site-packages/bpybuild/sources.py", line 265, in tags
        cls.BASE_REPO.list(rel_path="/tags") if
      File "/usr/local/lib/python3.7/site-packages/bpybuild/sources.py", line 264, in <listcomp>
        return [posixpath.join(cls.BASE_URL, "tags", _version) for _version in
      File "/Users/yuzhouguo/Library/Python/3.7/lib/python/site-packages/svn/common.py", line 341, in list
        [full_url_or_path]):
      File "/Users/yuzhouguo/Library/Python/3.7/lib/python/site-packages/svn/common.py", line 60, in run_command
        return self.external_command(cmd, environment=self.__env, **kwargs)
      File "/Users/yuzhouguo/Library/Python/3.7/lib/python/site-packages/svn/common_base.py", line 39, in external_command
        return_code, cmd, stdout))
    svn.exception.SvnException: Command failed with (72): ['svn', '--non-interactive', 'ls', 'https://svn.blender.org/svnroot/bf-blender//tags']
    svn: error: Failed to locate 'svn'.
    svn: error: The subversion command line tools are no longer provided by Xcode.
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.7/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hf/z6y_nh7s31v68qwvngk1s85w0000gn/T/pip-install-7t20rqx6/bpy_cd850d780e2c4c4d8bf1764790a94d28/setup.py'"'"'; __file__='"'"'/private/var/folders/hf/z6y_nh7s31v68qwvngk1s85w0000gn/T/pip-install-7t20rqx6/bpy_cd850d780e2c4c4d8bf1764790a94d28/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/hf/z6y_nh7s31v68qwvngk1s85w0000gn/T/pip-record-znq4la65/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/bpy Check the logs for full command output.
    Running setup.py install for bpy: finished with status 'error'
FINISHED
```
**And I do have xcode-select installed:**
```
yuzhouguo@Yuzhous-MacBook-Pro /u/l/C/p/3/bin [1]> xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```
**So as my svn:**
```
yuzhouguo@Yuzhous-MacBook-Pro /u/l/C/p/3/bin [1]> svn --version
svn, version 1.14.1 (r1886195)
   compiled Feb 11 2021, 04:53:16 on x86_64-apple-darwin19.6.0

Copyright (C) 2021 The Apache Software Foundation.
This software consists of contributions made by many people;
see the NOTICE file for more information.
Subversion is open source software, see http://subversion.apache.org/

The following repository access (RA) modules are available:

* ra_svn : Module for accessing a repository using the svn network protocol.
  - with Cyrus SASL authentication
  - handles 'svn' scheme
* ra_local : Module for accessing a repository on local disk.
  - handles 'file' scheme
* ra_serf : Module for accessing a repository via WebDAV protocol using serf.
  - using serf 1.3.9 (compiled with 1.3.9)
  - handles 'http' scheme
  - handles 'https' scheme

The following authentication credential caches are available:

* Mac OS X Keychain
```
Thank you for any help provided!

**Comment by TylerGubala** [comment]
It seems the problem here is the Python SVN module I rely on.

```
svn.exception.SvnException: Command failed with (72): ['svn', '--non-interactive', 'ls', 'https://svn.blender.org/svnroot/bf-blender//tags']
  svn: error: Failed to locate 'svn'.
  svn: error: The subversion command line tools are no longer provided by Xcode.
```

If you are installing on Python 3.7 you should be able to use my `wheel` files though. Not sure why PyDev didn't select that automatically. You can find them on the [Releases page](https://github.com/TylerGubala/blenderpy/releases/tag/v2.91a0)

**Comment by Kuro-Maii** [comment]
after running `pip install future-fstrings` (as suggested here: #91)
I ran into this same problem and I seem to be unable to resolve the issue by running `pip install svn`
so as suggested by @TylerGubala above here I tried the `wheel` from the releases page, installed all the dependencies from the blender wiki as per instructions for ubuntu
next I ran into the following:
```
pip install ~/Downloads/bpy-2.91a0-cp37-cp37m-manylinux2014_x86_64.whl && bpy_post_install
ERROR: bpy-2.91a0-cp37-cp37m-manylinux2014_x86_64.whl is not a supported wheel on this platform.
```

**Comment by Kuro-Maii** [comment]
after attempting the wheel I decided to retry the normal pip install:
```
pip install bpy && bpy_post_install
Collecting bpy
  Using cached bpy-0.0.0a0.tar.gz (19 kB)
Building wheels for collected packages: bpy
  Building wheel for bpy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a6jneffw/bpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a6jneffw/bpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-jxr1_k1n
       cwd: /tmp/pip-install-a6jneffw/bpy/
  Complete output (41 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/blenderpy
  copying blenderpy/__init__.py -> build/lib.linux-x86_64-3.8/blenderpy
  copying blenderpy/post_install.py -> build/lib.linux-x86_64-3.8/blenderpy
  running build_ext
  Preparing the build environment
  Searching for compatible Blender online (this will take a while)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-a6jneffw/bpy/setup.py", line 288, in <module>
      setup(name='bpy',
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 163, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-a6jneffw/bpy/setup.py", line 186, in run
      self.build_cmake(extension)
    File "/tmp/pip-install-a6jneffw/bpy/setup.py", line 220, in build_cmake
      raise Exception(f"{VERSION} bpy is not compatible with "
  Exception: 2.82 bpy is not compatible with Linux Python 3.8.6 (default, Jan 27 2021, 15:42:20)
  [GCC 10.2.0] 64bit
  ----------------------------------------
  ERROR: Failed building wheel for bpy
  Running setup.py clean for bpy
Failed to build bpy
Installing collected packages: bpy
    Running setup.py install for bpy ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a6jneffw/bpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a6jneffw/bpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-plqqyy2b/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/angel/.local/include/python3.8/bpy
         cwd: /tmp/pip-install-a6jneffw/bpy/
    Complete output (43 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/blenderpy
    copying blenderpy/__init__.py -> build/lib.linux-x86_64-3.8/blenderpy
    copying blenderpy/post_install.py -> build/lib.linux-x86_64-3.8/blenderpy
    running build_ext
    Preparing the build environment
    Searching for compatible Blender online (this will take a while)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-a6jneffw/bpy/setup.py", line 288, in <module>
        setup(name='bpy',
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-a6jneffw/bpy/setup.py", line 186, in run
        self.build_cmake(extension)
      File "/tmp/pip-install-a6jneffw/bpy/setup.py", line 220, in build_cmake
        raise Exception(f"{VERSION} bpy is not compatible with "
    Exception: 2.82 bpy is not compatible with Linux Python 3.8.6 (default, Jan 27 2021, 15:42:20)
    [GCC 10.2.0] 64bit
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a6jneffw/bpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a6jneffw/bpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-plqqyy2b/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/angel/.local/include/python3.8/bpy Check the logs for full command output.
```
seems that the instructions on what to install and in what order need clarification. as well as adding clarification that `bpy` requires a specific version of python

**Comment by Heath123** [comment]
`sudo apt install subversion` fixed this for me

**Comment by mathelehrer** [comment]
Same for me:
Once I installed the requirements shown on the wiki page
https://wiki.blender.org/wiki/Building_Blender/Linux/Ubuntu

(which includes subversion) the installation worked for me.

**Comment by AdamStormhardtGH** [comment]
if `sudo apt install subversion` is throwing java errors at you, 
you can also use `brew install svn` which successfully installed for me on OSX M1

**Comment by pecd** [comment]
@TylerGubala nice to meet you! Thanks for providing pre-release version of .whl build for Ubuntu. 

Do you know when "stable" build for Ubuntu will be released?

**Comment by J1-E1** [comment]
this could be solved by download "svn", may need to download different versions of blender through svn

‘brew install svn’

**Comment by ggand0** [comment]
Why does blenderpy require subversion in the first place?
Does it have any dependencies only accessible by svn?
https://wiki.blender.org/wiki/Tools/Subversion

**Comment by abhimanyuchadha96** [comment]
@AdamStormhardtGH Which python version are you running on your M1?
I am running 3.9 and am unable to install bpy.

**Comment by AdamStormhardtGH** [comment]
@abhimanyuchadha96 I'm on 3.9+ but have moved to use os system because this library kept causing weird issues. The SVN install partially fixed things but I think I celebrated a bit too soon =/ 

Now I do one of the following:

- Add blender's python install to my path and try to install all my other libraries on there (this circumvents the need to use this library entirely because all dependencies are pre-installed with every version of blender)
OR *and this is what I usually do now*
- Just use the blender python ingress to run my scripts this way. You'll get pipe errors when blender closes and the script is still working, but i had honestly had enough of troubleshooting and just wanted to get on with the automation jobs.
eg. 
```  
blender_job_command = f"blender {cwd}/src/blend/template_slide_scene.blend --python {cwd}/src/scripts/blender_ingress_point.py"  #arguments are acting weird so i'll just shuffle state with a file

subprocess.Popen(blender_job_command, shell=True, stdout=subprocess.PIPE)
```
OR when I'm really desperate
- copy paste into the scripts editor

All these approaches work on M1 2021 studio and laptop for me, but i'm mostly working with simple rendering, material manipulation, and the video editor functionality
