### ISSUE TITLE
future fstring missing

### ISSUE THREAD

**Issue by theottm** [TylerGubala/blenderpy#91]
Hi!

Same problem as stated [here.](https://blender.stackexchange.com/questions/169561/pip-install-bpy-not-working-lookuperror-unknown-encoding-future-fstrings) During installation future-fstring was missing and produced an error

`pip install bpy && bpy_post_install`

```
Collecting bpy
  Using cached https://files.pythonhosted.org/packages/4b/ed/ba6092b691acc5b157891421d9fde4a9dd5dcc8a8b93a4e8119fec261391/bpy-2.82.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/home/teddd/.pyenv/versions/3.7.0/lib/python3.7/tokenize.py", line 397, in find_cookie
        codec = lookup(encoding)
    LookupError: unknown encoding: future_fstrings
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/teddd/.pyenv/versions/3.7.0/lib/python3.7/tokenize.py", line 449, in open
        encoding, lines = detect_encoding(buffer.readline)
      File "/home/teddd/.pyenv/versions/3.7.0/lib/python3.7/tokenize.py", line 436, in detect_encoding
        encoding = find_cookie(second)
      File "/home/teddd/.pyenv/versions/3.7.0/lib/python3.7/tokenize.py", line 405, in find_cookie
        raise SyntaxError(msg)
    SyntaxError: unknown encoding for '/media/teddd/IHD/tmp/pip-install-kidjhmzn/bpy/setup.py': future_fstrings
```

`pip install future-fstrings` solved the problem. 

 OS: Debian Buster

**Comment by neevparikh** [comment]
@TylerGubala Might be worth adding to the instructions
